default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: tweeterclone_development


test:
  <<: *default
  database: tweeterclone_test
  

production:
  <<: *default
  database: tweeterclone_production
